{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "cloudflare-zero-trust-operator.namespace" . }}
  labels:
    {{- include "cloudflare-zero-trust-operator.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
{{- end }}
